// Package envelope provides an optional standard message envelope for NATS
// messages. It wraps arbitrary payloads with metadata (ID, timestamp, source,
// type, correlation ID) useful for tracing, auditing, and idempotency.
//
// Usage is opt-in — services that don't need an envelope can use raw
// natsx.Publish / typed.Publish directly.
package envelope

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"time"
)

// Envelope wraps a payload of type T with standard metadata.
type Envelope[T any] struct {
	// ID is a unique message identifier. Auto-generated by Wrap if empty.
	ID string `json:"id"`

	// Type describes the kind of payload (e.g. "order.created").
	Type string `json:"type,omitempty"`

	// Source identifies the originating service or component.
	Source string `json:"source,omitempty"`

	// CorrelationID links related messages across services.
	CorrelationID string `json:"correlation_id,omitempty"`

	// Timestamp is when the envelope was created (UTC).
	Timestamp time.Time `json:"timestamp"`

	// Data is the actual payload.
	Data T `json:"data"`
}

// Wrap creates an Envelope around data, auto-generating an ID and timestamp.
func Wrap[T any](data T) Envelope[T] {
	return Envelope[T]{
		ID:        generateID(),
		Timestamp: time.Now().UTC(),
		Data:      data,
	}
}

// WrapWith creates an Envelope with explicit metadata fields.
func WrapWith[T any](data T, msgType, source, correlationID string) Envelope[T] {
	return Envelope[T]{
		ID:            generateID(),
		Type:          msgType,
		Source:        source,
		CorrelationID: correlationID,
		Timestamp:     time.Now().UTC(),
		Data:          data,
	}
}

// Marshal serializes the envelope to JSON bytes.
func (e Envelope[T]) Marshal() ([]byte, error) {
	return json.Marshal(e)
}

// Unmarshal parses JSON bytes into an Envelope of type T.
func Unmarshal[T any](data []byte) (Envelope[T], error) {
	var env Envelope[T]
	if err := json.Unmarshal(data, &env); err != nil {
		return env, fmt.Errorf("envelope.Unmarshal: %w", err)
	}
	return env, nil
}

// generateID creates a random hex ID (16 bytes = 32 hex chars).
func generateID() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		// Fallback — extremely unlikely to fail.
		return fmt.Sprintf("%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(b)
}
